[dependencies]
  lucida = { path = "./libs/optics/v2" }
  lucida_macro = { path = "./libs/macro-optics/v2" }
  macro_test_utils = { path = "./libs/macro-test-utils/" }

[package]
  cjc-version = "0.57.3"
  compile-option = "-O2 --debug-macro"
  description = "Law test suite and benchmarks for the lucida optics library"
  link-option = ""
  name = "optics_experiments"
  output-type = "executable"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[target.x86_64-unknown-linux-gnu]
  [target.x86_64-unknown-linux-gnu.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]
