[workspace]
  members = ["core", "stdlib", "tests"]
  build-members = []
  test-members = []
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  target-dir = ""
  script-dir = ""

[dependencies]

[profile.build]
  performance_analysis = true


[profile.customized-option]
  rel = "-O2"
  dbg = "-O0 -g --debug-macro -Woff unused"
