[package]
  cjc-version = "0.57.3"
  compile-option = "--debug-macro"
  description = "lucida: optics core, composition table and stdlib"
  link-option = ""
  name = "lucida"
  output-type = "dynamic"
  override-compile-option = ""
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  license = ["MIT"]
  package-configuration = {}
